### ISSUE TITLE
Can't install in chrome

### ISSUE THREAD

**Issue by rsabhilash** [anuragdadheech/advantage-detector#1]
I tired to install it, but failed with following message

"Could not install package: 'UTILITY_PROCESS_CRASHED_WHILE_TRYING_TO_INSTALL'. Could not install package because a utility process crashed. Try restarting Chrome and trying again."

**Comment by anuragdadheech** [comment]
Hey! What's your chrome version. Did you install from webstore or built it from source?

**Comment by rsabhilash** [comment]
I updated chromium to latest version, its working now. Thanks for contacting.
